name: oracle_dba_versus_postgresql
services:
    pmm:
        image: percona/pmm-server:3
        # sadly no ARM image available
        platform: linux/amd64
        container_name: pmm
        volumes:
            - pmm_data:/srv
        ports:
            - 8443:8443
        environment:
            - PMM_ENABLE_UPDATES=0
        networks:
            - demo-net
        post_start:
            # The first sleep is pretty random, but need to wait until the stack is fully up before changing the password
            - command: sleep 1m
            - command: "bash -c '[ ! -h /usr/share/grafana/data ] && ln -s /srv/grafana /usr/share/grafana/data || echo linkalreadyexists'"
            - command: "bash -c '[ ! -f /srv/admin_password_changed ] && grafana cli --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini admin reset-admin-password demo123 || echo adminpasswordchanged'"
            - command: touch /srv/admin_password_changed
    etcd1:
        image: quay.io/coreos/etcd:v3.5.33
        container_name: etcd1
        command:
            - etcd
            - --name=etcd1
            - --data-dir=/etcd-data
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://etcd1:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://etcd1:2380
            - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
            - --initial-cluster-state=new
            - --initial-cluster-token=etcd-cluster-1
            - --auto-compaction-mode=periodic
            - --auto-compaction-retention=1h
        volumes:
            - etcd1_data:/etcd-data
        networks:
            - demo-net
    etcd2:
        image: quay.io/coreos/etcd:v3.5.33
        container_name: etcd2
        command:
            - etcd
            - --name=etcd2
            - --data-dir=/etcd-data
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://etcd2:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://etcd2:2380
            - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
            - --initial-cluster-state=new
            - --initial-cluster-token=etcd-cluster-1
            - --auto-compaction-mode=periodic
            - --auto-compaction-retention=1h
        volumes:
            - etcd2_data:/etcd-data
        networks:
            - demo-net
    etcd3:
        image: quay.io/coreos/etcd:v3.5.33
        container_name: etcd3
        command:
            - etcd
            - --name=etcd3
            - --data-dir=/etcd-data
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://etcd3:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://etcd3:2380
            - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
            - --initial-cluster-state=new
            - --initial-cluster-token=etcd-cluster-1
            - --auto-compaction-mode=periodic
            - --auto-compaction-retention=1h
        volumes:
            - etcd3_data:/etcd-data
        networks:
            - demo-net
    pg1:
        image: oracle_dba_vs_postgresql_pg
        container_name: pg1
        build:
            context: postgres/
        ports:
            - 15432:5432
        environment:
            - PATRONIHOST=pg1
        volumes:
            - pg1_data:/var/lib/pgsql/data
        networks:
            - demo-net
    pg2:
        image: oracle_dba_vs_postgresql_pg
        container_name: pg2
        build:
            context: postgres/
        ports:
            - 25432:5432
        environment:
            - PATRONIHOST=pg2
        volumes:
            - pg2_data:/var/lib/pgsql/data
        networks:
            - demo-net
    pgdog:
        image: ghcr.io/pgdogdev/pgdog:main
        container_name: pgdog
        ports:
            - 6432:6432
        networks:
            - demo-net
        volumes:
            - ./pgdog.toml:/pgdog/pgdog.toml
            - ./users.toml:/pgdog/users.toml

networks:
    demo-net:
        driver: bridge

volumes:
    etcd1_data:
    etcd2_data:
    etcd3_data:
    pg1_data:
    pg2_data:
    pmm_data:
